// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0

package repository

import ()

type Language struct {
	ID     string `db:"id" json:"id"`
	Base   string `db:"base" json:"base"`
	Region string `db:"region" json:"region"`
}

type Translation struct {
	WordID            string `db:"word_id" json:"word_id"`
	WordTranslationID string `db:"word_translation_id" json:"word_translation_id"`
}

type Word struct {
	ID         string `db:"id" json:"id"`
	LanguageID string `db:"language_id" json:"language_id"`
	Value      string `db:"value" json:"value"`
}
