// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0

package repository

import (
	"context"
)

type Querier interface {
	InsertTranslation(ctx context.Context, arg InsertTranslationParams) error
	InsertWord(ctx context.Context, arg InsertWordParams) error
	SelectSimilarWords(ctx context.Context, arg SelectSimilarWordsParams) ([]SelectSimilarWordsRow, error)
	SelectTranslations(ctx context.Context, arg SelectTranslationsParams) ([]Word, error)
	SelectWordIdByWordLangRegion(ctx context.Context, arg SelectWordIdByWordLangRegionParams) (string, error)
}

var _ Querier = (*Queries)(nil)
