// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0

package repository

import (
	"context"
)

type Querier interface {
	InsertLanguage(ctx context.Context, arg InsertLanguageParams) error
	InsertTranslation(ctx context.Context, arg InsertTranslationParams) error
	InsertWord(ctx context.Context, arg InsertWordParams) error
}

var _ Querier = (*Queries)(nil)
